### PR TITLE
Added hangman.py in Resources

### PR DESCRIPTION
**Pull request by DebugAgrawal**
**An interactive hangman along with GUI using turtle library**
Screenshot (403)

### CODE REVIEW

**Comment by DebugAgrawal** [comment]
### Happy coding 😊

**Comment by DebugAgrawal** [comment]
Hey on the Hacktoberfest page

this repo is marked as Ineligible Kindly cross check it ?

**Comment by gawangnich** [comment]
> Hey on the Hacktoberfest page
> 
> this repo is marked as Ineligible Kindly cross check it ?
> 
> 
> 

Can you check it again ? , Because my friend open PR on this repository and it's okay

**Comment by DebugAgrawal** [comment]
> > Hey on the Hacktoberfest page
> > this repo is marked as Ineligible Kindly cross check it ?
> > 
> > 
> 
> Can you check it again ? , Because my friend open PR on this repository and it's okay

Can you please label it as **hacktoberfest-accepted**

**Comment by gawangnich** [comment]
> > > Hey on the Hacktoberfest page
> > > this repo is marked as Ineligible Kindly cross check it ?
> > > 
> > > 
> > 
> > 
> > Can you check it again ? , Because my friend open PR on this repository and it's okay
> 
> Can you please label it as **hacktoberfest-accepted**

Okay no problem

**Comment by DebugAgrawal** [comment]
> > > > Hey on the Hacktoberfest page
> > > > this repo is marked as Ineligible Kindly cross check it ?
> > > > 
> > > > 
> > > 
> > > 
> > > Can you check it again ? , Because my friend open PR on this repository and it's okay
> > 
> > 
> > Can you please label it as **hacktoberfest-accepted**
> 
> Okay no problem

> Thanks for considering 😊🚀

_Happy Contributing_

**Pull request merged**
